{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autotune.fullname" . }}-secret
  labels:
    {{- include "autotune.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTOTUNE_ADMIN_KEY: {{ required "adminKey is required when existingSecret is not set" .Values.adminKey | quote }}
{{- end }}
