#!/usr/bin/env bash
# autotune setup wizard — first-run configuration helper
#
# Generates a secure AUTOTUNE_ADMIN_KEY and writes a .env file.
# Safe to re-run: will not overwrite an existing .env unless you confirm.
#
# Usage: ./setup.sh [--non-interactive]

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
if [ -t 1 ] && command -v tput &>/dev/null; then
  BOLD=$(tput bold); RESET=$(tput sgr0)
  CYAN=$(tput setaf 6); GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; RESET=""; CYAN=""; GREEN=""; YELLOW=""; RED=""
fi

# ── Helpers ───────────────────────────────────────────────────────────────────
say()  { printf "%s\n" "$*"; }
info() { say "  ${CYAN}▸${RESET} $*"; }
ok()   { say "  ${GREEN}✓${RESET} $*"; }
warn() { say "  ${YELLOW}⚠${RESET}  $*"; }
die()  { say "  ${RED}✗${RESET}  $*" >&2; exit 1; }

# ── Non-interactive mode ──────────────────────────────────────────────────────
NON_INTERACTIVE=0
for arg in "$@"; do
  [[ "$arg" == "--non-interactive" ]] && NON_INTERACTIVE=1
done

ask() {
  # ask <prompt> <default>  → echoes answer (default if non-interactive)
  local prompt="$1" default="$2" answer
  if [[ $NON_INTERACTIVE -eq 1 ]]; then
    echo "$default"
    return
  fi
  read -r -p "  ${BOLD}${prompt}${RESET} [${default}]: " answer
  echo "${answer:-$default}"
}

# ── Banner ────────────────────────────────────────────────────────────────────
say ""
say "${BOLD}${CYAN}autotune${RESET} — first-run setup wizard"
say "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
say ""

# ── Check for Python ──────────────────────────────────────────────────────────
PYTHON=""
for py in python3 python; do
  if command -v "$py" &>/dev/null && "$py" -c "import sys; sys.exit(0 if sys.version_info >= (3,9) else 1)" 2>/dev/null; then
    PYTHON="$py"
    break
  fi
done
[[ -z "$PYTHON" ]] && die "Python 3.9+ is required. Install it from https://python.org and re-run."
ok "Python found: $($PYTHON --version)"

# ── Existing .env guard ───────────────────────────────────────────────────────
ENV_FILE="$(pwd)/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE"
  overwrite=$(ask "Overwrite it? (yes/no)" "no")
  if [[ "$overwrite" != "yes" ]]; then
    info "Keeping existing .env — nothing changed."
    say ""
    say "  To reconfigure, delete .env and re-run ./setup.sh"
    say ""
    exit 0
  fi
fi

# ── Generate admin key ────────────────────────────────────────────────────────
info "Generating a secure AUTOTUNE_ADMIN_KEY (48-char URL-safe token)…"
ADMIN_KEY=$($PYTHON -c "import secrets; print(secrets.token_urlsafe(48))")
ok "Admin key generated (${#ADMIN_KEY} chars)"

# ── API key enforcement ───────────────────────────────────────────────────────
say ""
say "  ${BOLD}API Key Enforcement${RESET}"
say "  When enabled, every /v1/* request must include a valid API key."
say "  Recommended for team deployments; optional for personal use."
say ""
require_key=$(ask "Require API keys for inference requests? (yes/no)" "yes")
if [[ "$require_key" == "yes" ]]; then
  REQUIRE_KEY_VAL="1"
  ok "API key enforcement: ON"
else
  REQUIRE_KEY_VAL="0"
  warn "API key enforcement: OFF (any client that can reach the port can use your models)"
fi

# ── Port ──────────────────────────────────────────────────────────────────────
say ""
AUTOTUNE_PORT=$(ask "Port to expose autotune on" "8765")
ok "Port: $AUTOTUNE_PORT"

# ── Write .env ────────────────────────────────────────────────────────────────
say ""
info "Writing $ENV_FILE …"

cat > "$ENV_FILE" <<EOF
# autotune environment — generated by ./setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Keep this file secret and never commit it to version control.

# ── Admin key (dashboard login + admin API) ───────────────────────────────────
AUTOTUNE_ADMIN_KEY=${ADMIN_KEY}

# ── API key enforcement ───────────────────────────────────────────────────────
# 1 = every /v1/* request must include Authorization: Bearer <key>
# 0 = open access (personal / trusted-network use only)
AUTOTUNE_REQUIRE_API_KEY=${REQUIRE_KEY_VAL}

# ── Server port ───────────────────────────────────────────────────────────────
AUTOTUNE_PORT=${AUTOTUNE_PORT}

# ── Optional: custom Ollama URL (default: http://localhost:11434) ─────────────
# AUTOTUNE_OLLAMA_URL=http://ollama:11434

# ── Optional: self-hosted telemetry (Supabase) ────────────────────────────────
# AUTOTUNE_SUPABASE_URL=https://your-project-ref.supabase.co
# AUTOTUNE_SUPABASE_KEY=your-anon-key
EOF

ok ".env written"

# ── .gitignore guard ──────────────────────────────────────────────────────────
GITIGNORE="$(pwd)/.gitignore"
if [[ -f "$GITIGNORE" ]] && grep -q "^\.env$" "$GITIGNORE"; then
  ok ".env is already in .gitignore"
elif [[ -f "$GITIGNORE" ]]; then
  echo ".env" >> "$GITIGNORE"
  ok "Added .env to .gitignore"
fi

# ── Next steps ────────────────────────────────────────────────────────────────
say ""
say "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
say "${GREEN}${BOLD}Setup complete!${RESET}  Here's what to do next:"
say ""

if command -v docker &>/dev/null && command -v docker-compose &>/dev/null \
   || (command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1); then
  say "  ${BOLD}Personal / single-machine:${RESET}"
  say "    docker compose --profile single up -d"
  say ""
  say "  ${BOLD}Team deployment (autotune + Ollama + nginx):${RESET}"
  say "    docker compose --profile team up -d"
  say ""
else
  say "  ${BOLD}Start autotune:${RESET}"
  say "    autotune serve              # local install"
  say "    # or: uvicorn autotune.api.server:app --port $AUTOTUNE_PORT"
  say ""
fi

say "  ${BOLD}Sign in to the dashboard:${RESET}"
say "    http://localhost:${AUTOTUNE_PORT}/dashboard"
say "    Password: your AUTOTUNE_ADMIN_KEY (saved in .env)"
say ""

if [[ "$REQUIRE_KEY_VAL" == "1" ]]; then
  say "  ${BOLD}Create your first API key:${RESET}"
  say "    Sign in to the dashboard → New Key"
  say ""
fi

say "  ${BOLD}Test the gateway:${RESET}"
say "    curl http://localhost:${AUTOTUNE_PORT}/health"
say ""
say "  ${BOLD}Docs:${RESET}  https://github.com/TanavChinthapatla/local-llm-optimizer#readme"
say ""
