# This file is auto-generated by the publish.yml GitHub Actions workflow
# using homebrew-pypi-poet (https://github.com/tdsmith/homebrew-pypi-poet).
#
# To install:
#   brew tap tanavc1/autotune
#   brew install llm-autotune
#
# Or one-liner:
#   brew install tanavc1/autotune/llm-autotune

class LlmAutotune < Formula
  include Language::Python::Virtualenv

  desc "Automatic local-LLM inference configuration recommender"
  homepage "https://github.com/tanavc1/local-llm-autotune"
  url "https://files.pythonhosted.org/packages/source/l/llm-autotune/llm_autotune-0.1.0.tar.gz"
  sha256 "PLACEHOLDER"  # filled automatically by publish.yml after PyPI upload
  license "MIT"

  depends_on "python@3.12"

  # Resource SHAs are auto-populated by the publish workflow via `poet -f llm-autotune`.
  # Do not edit this file by hand — push a new tag to trigger regeneration.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/autotune --version")
  end
end
